### ISSUE TITLE
如何获取命令下发目标设备的信息

### ISSUE THREAD

**Issue by homtoyat** [aliyun/linkedge-thing-access-sdk-python#2]
从平台下发命令给连接到边缘网关的一个设备时，驱动如果获取到该命令是给哪个设备的，怎么得到目标设备的id等信息？在getProperties方法中，只能获取到在物模型中定义的属性字段，得不到设备的id?

期待您的解答，谢谢！

**Comment by back1127** [comment]
您可以将目标设备的id在初始化的时候传入，当调用getProperties方式时，会调用到目标设备的getProperties函数，所以直接访问self.id就是当前目标设备的id
